version: '3'

services:
  master:
    image: 192.168.123.251/daocloud/hadoop-master:4.5
    ports:
      - "9870:9870"
      - "8088:8088"
      - "19888:19888"
      - "8188:8188"
    container_name: "master"
  slave1:
    image: 192.168.123.251/daocloud/hadoop-slave:4.5
    container_name: "slave1"
    depends_on:
      - master
    ports:
      - "9901:9864"
      - "8041:8042"
  slave2:
    image: 192.168.123.251/daocloud/hadoop-slave:4.5
    container_name: "slave2"
    depends_on:
      - master
    ports:
      - "9902:9864"
      - "8042:8042"
  slave3:
    image: 192.168.123.251/daocloud/hadoop-slave:4.5
    container_name: "slave3"
    depends_on:
      - master
    ports:
      - "9903:9864"
      - "8043:8042"

